/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Metadata } from "./Metadata";
import { MetadataCountArgs } from "./MetadataCountArgs";
import { MetadataFindManyArgs } from "./MetadataFindManyArgs";
import { MetadataFindUniqueArgs } from "./MetadataFindUniqueArgs";
import { CreateMetadataArgs } from "./CreateMetadataArgs";
import { UpdateMetadataArgs } from "./UpdateMetadataArgs";
import { DeleteMetadataArgs } from "./DeleteMetadataArgs";
import { DataFindManyArgs } from "../../data/base/DataFindManyArgs";
import { Data } from "../../data/base/Data";
import { UpdateDataArgs } from "../../data/base/UpdateDataArgs";
import { MetadataService } from "../metadata.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Metadata)
export class MetadataResolverBase {
  constructor(
    protected readonly service: MetadataService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Metadata",
    action: "read",
    possession: "any",
  })
  async _metadataItemsMeta(
    @graphql.Args() args: MetadataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Metadata])
  @nestAccessControl.UseRoles({
    resource: "Metadata",
    action: "read",
    possession: "any",
  })
  async metadataItems(
    @graphql.Args() args: MetadataFindManyArgs
  ): Promise<Metadata[]> {
    return this.service.metadataItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Metadata, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Metadata",
    action: "read",
    possession: "own",
  })
  async metadata(
    @graphql.Args() args: MetadataFindUniqueArgs
  ): Promise<Metadata | null> {
    const result = await this.service.metadata(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Metadata)
  @nestAccessControl.UseRoles({
    resource: "Metadata",
    action: "create",
    possession: "any",
  })
  async createMetadata(
    @graphql.Args() args: CreateMetadataArgs
  ): Promise<Metadata> {
    return await this.service.createMetadata({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Metadata)
  @nestAccessControl.UseRoles({
    resource: "Metadata",
    action: "update",
    possession: "any",
  })
  async updateMetadata(
    @graphql.Args() args: UpdateMetadataArgs
  ): Promise<Metadata | null> {
    try {
      return await this.service.updateMetadata({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Metadata)
  @nestAccessControl.UseRoles({
    resource: "Metadata",
    action: "delete",
    possession: "any",
  })
  async deleteMetadata(
    @graphql.Args() args: DeleteMetadataArgs
  ): Promise<Metadata | null> {
    try {
      return await this.service.deleteMetadata(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Data], { name: "dataItems" })
  @nestAccessControl.UseRoles({
    resource: "Data",
    action: "read",
    possession: "any",
  })
  async findDataItems(
    @graphql.Parent() parent: Metadata,
    @graphql.Args() args: DataFindManyArgs
  ): Promise<Data[]> {
    const results = await this.service.findDataItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.Mutation(() => UpdateDataArgs)
  async PatchMetadata(
    @graphql.Args()
    args: UpdateDataArgs
  ): Promise<UpdateDataArgs> {
    return this.service.PatchMetadata(args);
  }
}
